# Generated by Django 4.1.1 on 2022-11-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('video', models.FileField(upload_to='video/', verbose_name='ویدیو')),
                ('views', models.PositiveBigIntegerField(default=1, verbose_name='بازدید')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name': 'ویدیو ها',
                'verbose_name_plural': 'ویدیو',
            },
        ),
    ]
