# Generated by Django 4.1.3 on 2022-12-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ManyToManyField(to='videos.category', verbose_name='دسته بندی'),
        ),
    ]
