# Generated by Django 4.1.3 on 2022-12-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ManyToManyField(related_name='videos', to='videos.category', verbose_name='دسته بندی'),
        ),
    ]
