# Generated by Django 4.1.3 on 2023-04-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
