# Generated by Django 4.1.3 on 2023-04-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_remove_video_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='views',
        ),
    ]
