# Generated by Django 4.1.3 on 2022-11-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_video_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AddField(
            model_name='video',
            name='body',
            field=models.TextField(default=4, max_length=100, verbose_name='متن'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.BooleanField(blank=True, null=True, verbose_name='وضیعت'),
        ),
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name='ساعت'),
        ),
    ]
