# Generated by Django 4.1.3 on 2022-11-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_video_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='about_video',
            field=models.TextField(default=9, verbose_name='درباره فیلم'),
            preserve_default=False,
        ),
    ]
