# Generated by Django 4.1.3 on 2023-05-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_remove_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ManyToManyField(related_name='categorise', to='videos.category', verbose_name='دسته بندی ها'),
        ),
    ]
