# Generated by Django 4.1.3 on 2022-11-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_alter_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='username',
            field=models.CharField(default=8, max_length=200, verbose_name='نام کاربری'),
            preserve_default=False,
        ),
    ]
