# Generated by Django 4.1.3 on 2022-11-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_video_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='username',
        ),
    ]
