# Generated by Django 4.1.3 on 2022-11-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userteacher'),
        ('videos', '0018_alter_video_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user_author',
            field=models.ManyToManyField(default=True, related_name='about', to='account.userteacher', verbose_name='نویسنده'),
        ),
    ]
