# Generated by Django 4.1.3 on 2022-11-26 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0019_video_user_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user_author',
        ),
    ]
