# Generated by Django 4.1.3 on 2022-11-27 21:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0021_commit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commit',
            new_name='Comment',
        ),
    ]
