# Generated by Django 4.1.3 on 2022-11-30 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0025_alter_comment_options_alter_video_views_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='متن اعلان')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_admin', models.BooleanField(default=True)),
                ('active', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='videos.video', verbose_name='فعال هست یا خیر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
            options={
                'ordering': ('-active',),
            },
        ),
    ]
