# Generated by Django 4.1.3 on 2023-04-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, null=True, verbose_name='نام کاربری')),
                ('number', models.CharField(max_length=12, verbose_name='شماره تلفن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ImageUser/')),
                ('author', models.CharField(max_length=200)),
                ('about_user', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر ها',
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, null=True)),
                ('number', models.CharField(max_length=11, verbose_name='شماره')),
                ('code', models.SmallIntegerField(verbose_name='کد')),
                ('expiration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'کدتاید',
            },
        ),
    ]
