# Generated by Django 4.1.3 on 2022-11-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='نام کاربری'),
        ),
    ]
