# Generated by Django 4.1.3 on 2023-01-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_user',
            field=models.EmailField(default=1, max_length=254, verbose_name='ایمیل'),
            preserve_default=False,
        ),
    ]
