# Generated by Django 4.1.3 on 2022-11-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_profile_alter_user_number_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile',
            new_name='image',
        ),
    ]
