# Generated by Django 4.1.3 on 2023-01-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0004_user_email_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_user',
        ),
    ]
