# Generated by Django 4.1.3 on 2022-11-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('about_user', models.TextField()),
            ],
        ),
    ]
