# Generated by Django 4.1.3 on 2022-11-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userteacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTeacher',
        ),
        migrations.AddField(
            model_name='user',
            name='about_user',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='author',
            field=models.CharField(default=22, max_length=200),
            preserve_default=False,
        ),
    ]
