# Generated by Django 4.1.3 on 2022-11-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_delete_userteacher_user_about_user_user_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ImageUser/'),
        ),
    ]
